sudo: false

language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

before_install:
  - npm install codecov.io coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

test:
  override:
    yarn add --force phantomjs-prebuilt
    yarn test

branches:
  only:
    - master
